// The standard numbers in one go → docs/BENCH.md (a table you can diff).
//   node tools/bench.mjs [--cfg=detect.lam:0.4,...] [--out=docs/BENCH.md] [--print]
// Runs the eval tools in parallel (each is a separate process) and keeps a
// clearly marked section for the synthetic-chord bench (tools/eval_synth.mjs)
// untouched if it is already there.
import fs from 'node:fs';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const ROOT = path.resolve(new URL('..', import.meta.url).pathname);
const args = Object.fromEntries(process.argv.slice(2).map(a => { const m = /^--([^=]+)(?:=(.*))?$/.exec(a); return m ? [m[1], m[2] ?? true] : [a, true]; }));
const OUT = path.resolve(ROOT, args.out || 'docs/BENCH.md');
const CFG = args.cfg ? [`--cfg=${args.cfg}`] : [];
const run = promisify(execFile);
const tool = async (name, extra) => {
  const t0 = Date.now();
  const { stdout } = await run(process.execPath, [path.join(ROOT, 'tools', name), ...extra, ...CFG], { cwd: ROOT, maxBuffer: 64 << 20 });
  return { out: stdout, secs: (Date.now() - t0) / 1000 };
};

const MYSONG = 'basic,Asus4,Asus2,Am7,Gsus4,Dsus2,Fsus4,Fmaj7,Cmaj7,Em7';
const SETS = [
  ['basic (practice default)', 'basic'],
  ['all 53 (listen mode)', null],
  ['basic + sus + maj7 + min7 + 7th', 'basic,sus,maj7,minor7,seventh'],
  ['"my song" preset + basic', MYSONG],
];

const hasAudio = fs.existsSync(path.join(ROOT, 'testdata/audio')) && fs.readdirSync(path.join(ROOT, 'testdata/audio')).some(f => f.endsWith('.wav'));
const t0 = Date.now();
const lines = [];
const { execFileSync } = await import('node:child_process');
const commit = (() => { try { return execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim(); } catch { return '?'; } })();
const dirty = (() => { try { return execFileSync('git', ['status', '--porcelain', '--', 'src', 'data'], { cwd: ROOT, encoding: 'utf8' }).trim() ? ' (uncommitted changes in src/ or data/)' : ''; } catch { return ''; } })();

lines.push('# Benchmarks', '', `Generated by \`node tools/bench.mjs${args.cfg ? ` --cfg=${args.cfg}` : ''}\` at ${new Date().toISOString()} on commit ${commit}${dirty}.`, '',
  'GuitarSet numbers (Xi et al. 2018, CC-BY 4.0; the subset fetched by `testdata/fetch_guitarset.py`). "Open subset" = the SS3 / Rock3 / Rock1 progressions, frames with ≥3 strings ringing; "instructed" = lead-sheet chords, "performed" = what the player actually voiced. All numbers use the app\'s own scorer (`src/detect.js`) and `src/config.js`.', '');

if (!hasAudio) {
  lines.push('> testdata/audio has no WAVs — GuitarSet sections skipped. Run `python3 testdata/fetch_guitarset.py` (≈3 min) and re-run.', '');
} else {
  const jobs = {
    chords: Promise.all(SETS.map(([, c]) => tool('eval_chords.mjs', c ? [`--chords=${c}`] : []))),
    families: tool('eval_chords.mjs', ['--subset=all', '--gt=performed', '--chords=basic,maj7,minor7,seventh', '--dump=app']),
    familiesAll: tool('eval_chords.mjs', ['--subset=all', '--gt=performed', '--dump=app']),
    hold: tool('eval_hold.mjs', ['--minseg=2']),
    listen: tool('eval_listen.mjs', []),
    calBasic: tool('calibrate.mjs', ['--chords=basic']),
    calAll: tool('calibrate.mjs', []),
  };
  const R = Object.fromEntries(await Promise.all(Object.entries(jobs).map(async ([k, p]) => [k, await p])));
  const pct = (re, s) => { const m = re.exec(s); return m ? m[1] + '%' : '?'; };

  lines.push('## Chord accuracy by candidate set (open subset, instructed labels)', '', '| candidates | frame accuracy | old chroma+cosine detector (always all 53) |', '|---|---|---|');
  SETS.forEach(([label], i) => { const o = R.chords[i].out; lines.push(`| ${label} | ${pct(/\bapp=([\d.]+)%/, o)} | ${pct(/\bold=([\d.]+)%/, o)} |`); });
  lines.push('', 'Every extra candidate is a chance to be wrong: practice mode scores only the ticked chords plus the basic nine; listen mode scores all 53.', '');

  const fam = (o) => { const m = /by GT family: (.*)/.exec(o); return m ? m[1] : '?'; };
  lines.push('## Extended chords (all files, performed labels)', '', '| candidates | recall by family of the played chord |', '|---|---|',
    `| basic + maj7 + min7 + 7th | ${fam(R.families.out)} |`, `| all 53 | ${fam(R.familiesAll.out)} |`, '',
    'GuitarSet\'s 7th chords are jazz voicings (inner strings, often rootless); its sus chords are brief ornaments, so sus recall here is not a clean measurement. See the synthetic bench below for open-position voicings.', '');

  const hold = /^app\s+(\d+)%\s+(\d+)%\s+([\d.]+)s \/ ([\d.]+)s/m.exec(R.hold.out);
  lines.push('## Practice matching (StableRule, chord segments ≥ 2 s, basic candidates)', '', '| matched | wrong-chord fires | time to match p50 / p90 |', '|---|---|---|',
    hold ? `| ${hold[1]}% | ${hold[2]}% | ${hold[3]} s / ${hold[4]} s |` : '| ? | ? | ? |', '');

  const listenRows = R.listen.out.split('\n').filter(l => /^\s*\d+\/\d+/.test(l)).map(l => l.trim().split(/\s+/));
  lines.push('## Listen-mode display hold (all 53 candidates)', '', '| show / gap ms | shown | right (all frames) | right (when shown) | display changes per chord |', '|---|---|---|---|---|');
  for (const r of listenRows) lines.push(`| ${r[0]} | ${r[1]} | ${r[2]} | ${r[3]} | ${r[4]} |`);
  lines.push('', 'The app uses `CONFIG.listen.showMs / gapMs`.', '');

  const cal = (o, thr) => { const m = new RegExp(`^${thr}\\s+(\\d+)%\\s+(\\d+)%`, 'm').exec(o); return m ? [m[1] + '%', m[2] + '%'] : ['?', '?']; };
  lines.push('## Confidence threshold (open subset)', '', '| candidates | threshold | coverage of chord frames | precision of verdicts |', '|---|---|---|---|');
  for (const thr of ['0.30', '0.35', '0.40']) { const [c, p] = cal(R.calBasic.out, thr); lines.push(`| basic | ${thr} | ${c} | ${p} |`); }
  for (const thr of ['0.30', '0.35', '0.40']) { const [c, p] = cal(R.calAll.out, thr); lines.push(`| all 53 | ${thr} | ${c} | ${p} |`); }
  lines.push('', 'The sensitivity slider default (55) is 0.35 (`CONFIG.sensitivity`).', '');
  const secs = Object.entries(R).map(([k, r]) => `${k} ${(Array.isArray(r) ? r.reduce((a, x) => a + x.secs, 0) : r.secs).toFixed(0)}s`).join(', ');
  lines.push(`_Tool times: ${secs}; wall ${((Date.now() - t0) / 1000).toFixed(0)} s._`, '');
}

// keep the synthetic bench section if the synth tool wrote one
const START = '<!-- synth-bench:start -->', END = '<!-- synth-bench:end -->';
let synth = `${START}\n_No synthetic bench yet — \`node tools/eval_synth.mjs\` writes this section._\n${END}`;
if (fs.existsSync(OUT)) { const old = fs.readFileSync(OUT, 'utf8'); const a = old.indexOf(START), b = old.indexOf(END); if (a >= 0 && b > a) synth = old.slice(a, b + END.length); }
lines.push('## Synthetic chord bench (real per-string notes)', '', synth, '', 'Regenerate everything: `npm run bench`. Unit tests: `npm test`.');

const text = lines.join('\n') + '\n';
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, text);
if (args.print) process.stdout.write(text);
console.log(`wrote ${path.relative(ROOT, OUT)} (${((Date.now() - t0) / 1000).toFixed(0)} s)`);
